import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid md:grid-cols-[2fr,9fr] grid-cols-1 font-sans ">
          <div className="bg-white min-h-screen sticky top-0 left-0 md:block hidden">
            <Sidebar />
          </div>
          <div className="p-6">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
